### ISSUE TITLE
您好,目前的模型A10,24G显存可以支持预测功能吗?

### ISSUE THREAD

**Issue by yuanqingye** [xuyingjie521/Cornucopia-LLaMA-Fin-Chinese#18]
作者您好,首先非常致敬您的工作,也感谢开源
很感兴趣,想看看模型效果,但是不知购买A10这样一个相对有些老GPU能否支持该模型预测吗?目前暂时不考虑训练的问题
因为毕竟也是不少的钱,所以想问下这个配置是否能支持,再进行购买

**Comment by jerry1993-tech** [comment]
> 作者您好,首先非常致敬您的工作,也感谢开源 很感兴趣,想看看模型效果,但是不知购买A10这样一个相对有些老GPU能否支持该模型预测吗?目前暂时不考虑训练的问题 因为毕竟也是不少的钱,所以想问下这个配置是否能支持,再进行购买

谢谢您的喜爱和支持，24G显存的GPU可以满足模型推理的，一般7B模型显存占用为12～14G左右，13B模型占用为22G左右，后续我们也会出量化版本，需要显存就更低。

**Comment by jerry1993-tech** [comment]
> 作者您好,首先非常致敬您的工作,也感谢开源 很感兴趣,想看看模型效果,但是不知购买A10这样一个相对有些老GPU能否支持该模型预测吗?目前暂时不考虑训练的问题 因为毕竟也是不少的钱,所以想问下这个配置是否能支持,再进行购买

谢谢你的喜爱和支持，24G显存的GPU用于推理和低秩微调都足够的，给您一些模型推理时所需显存的占用情况：6B、7B模型大约12～14G显存占用，13B模型大约22G显存占用；后续我们也会发布量化版本的模型，需要显存更少。
希望我的回答对您有帮助～

**Comment by yuanqingye** [comment]
> > 作者您好,首先非常致敬您的工作,也感谢开源 很感兴趣,想看看模型效果,但是不知购买A10这样一个相对有些老GPU能否支持该模型预测吗?目前暂时不考虑训练的问题 因为毕竟也是不少的钱,所以想问下这个配置是否能支持,再进行购买
> 
> 谢谢你的喜爱和支持，24G显存的GPU用于推理和低秩微调都足够的，给您一些模型推理时所需显存的占用情况：6B、7B模型大约12～14G显存占用，13B模型大约22G显存占用；后续我们也会发布量化版本的模型，需要显存更少。 希望我的回答对您有帮助～

好的,十分謝謝您的回復!
關於微調方面,這邊有沒有什麽推薦的顯存配置呢?
