### ISSUE TITLE
Do we have any opportunities for cooperation ? 

### ISSUE THREAD

**Issue by luyangxxt** [xuyingjie521/Cornucopia-LLaMA-Fin-Chinese#19]
Hello, we are an algorithm research team currently working on large language models in the field of new energy. We are very interested in your research. May I ask if your research can be transferred to our vertical field of new energy? Do we know of any opportunities for further cooperation?

**Comment by jerry1993-tech** [comment]
Thank you very much for your interest and trust. Currently, our project will have major updates by the end of the year, including code frameworks and large model weights. I am also very interested in your field of new energy, and I have some ideas as well. I look forward to the opportunity to collaborate with you!

**Comment by jerry1993-tech** [comment]
> Hello, we are an algorithm research team currently working on large language models in the field of new energy. We are very interested in your research. May I ask if your research can be transferred to our vertical field of new energy? Do we know of any opportunities for further cooperation?

Thank you very much for your interest and trust. Currently, our project will have major updates by the end of the year, including code frameworks and large model weights. I am also very interested in your field of new energy, and I have some ideas as well. I look forward to the opportunity to collaborate with you!

**Comment by jerry1993-tech** [comment]
> Hello, we are an algorithm research team currently working on large language models in the field of new energy. We are very interested in your research. May I ask if your research can be transferred to our vertical field of new energy? Do we know of any opportunities for further cooperation?

Could you please leave your contact information, such as WeChat or QQ number? Tranks！
